### ISSUE TITLE
I can't get it to start

### ISSUE THREAD

**Issue by bovas85** [alphillips/chatty-bot#1]
When I run heroku logs I always get App Crashed error H10

I tried adding a Procfile with node index.js as start parameter but I get error, cannot find module chatty-bot.

log:
`2016-05-13T09:36:38.597387+00:00 heroku[web.1]: Starting process with command`node index.js`
2016-05-13T09:36:40.630035+00:00 app[web.1]: module.js:341
2016-05-13T09:36:40.630054+00:00 app[web.1]:     throw err;
2016-05-13T09:36:40.630059+00:00 app[web.1]:     ^
2016-05-13T09:36:40.630060+00:00 app[web.1]:
2016-05-13T09:36:40.630068+00:00 app[web.1]: Error: Cannot find module 'chatty-bot'
2016-05-13T09:36:40.630075+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-05-13T09:36:40.630076+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-05-13T09:36:40.630077+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-05-13T09:36:40.630077+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-05-13T09:36:40.630078+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:1:79)
2016-05-13T09:36:40.630078+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-05-13T09:36:40.630079+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-05-13T09:36:40.630079+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-05-13T09:36:40.630079+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-05-13T09:36:40.630080+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-05-13T09:36:41.541730+00:00 heroku[web.1]: State changed from starting to crashed
2016-05-13T09:36:41.523050+00:00 heroku[web.1]: Process exited with status 1`

**Comment by bovas85** [comment]
I managed to fix it adding a Procfile with 
web: node index.js

and the tokens were without '' so it was not recognizing it.
